apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: alainredacre/baccend:384afcf99ebc5b5284992e40744ab5d710a76e6e
        ports:
        - containerPort: 3000