apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: alainredacre/tfacca:7177c137d8a82e8d51bf7b6572da2f2f9f71f461
        ports:
        - containerPort: 80