apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  namespace: kube-system
spec:
  serviceAccountName: fluent-bit
  containers:
  - name: curl-container
    image: curlimages/curl
    command: ["sh", "-c", "sleep 3600"]
