name: CI/CD Pipeline

on:
  push:
    branches: [ develop ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Frontend Docker Image Please
      uses: docker/build-push-action@v2
      with:
        context: ./tfacca
        file: ./tfacca/Dockerfile
        push: true
        tags: alainredacre/tfacca:${{ github.sha }}

    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./baccend
        file: ./baccend/Dockerfile
        push: true
        tags: alainredacre/baccend:${{ github.sha }}

    - name: Update Kubernetes Deployment Manifest for Frontend
      run: |
        sed -i "s|alainredacre/tfacca:.*|alainredacre/tfacca:${{ github.sha }}|g" ./k8s/frontend-deployment.yaml

    - name: Update Kubernetes Deployment Manifest for Backend
      run: |
        sed -i "s|alainredacre/baccend:.*|alainredacre/baccend:${{ github.sha }}|g" ./k8s/backend-deployment.yaml

    - name: Commit and Push Manifest Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./k8s/frontend-deployment.yaml
        git add ./k8s/backend-deployment.yaml
        git commit -m "Update deployment image tag to ${{ github.sha }}"
        git push --set-upstream origin HEAD:develop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}