name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Frontend Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./tfacca
        file: ./tfacca/Dockerfile
        push: true
        tags: user/frontend:latest

    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./baccend
        file: ./baccend/Dockerfile
        push: true
        tags: user/backend:latest
